### ISSUE TITLE
有。。更新吗

### ISSUE THREAD

**Issue by lostcc** [BeniceSoft/OpenAuthing#1]
qaq

**Comment by lostcc** [comment]
看了一天，感觉完成度比较高，就是有几个问题，
1、缺失种子数据，自己做数据需要花费大量精力
2、前端跳转没太看明白，是通过反向代理请求后端吗，但是好像后端会把所有请求重定向掉，导致访问不到后端接口，前端是不是需要设置一些参数？

**Comment by zengande** [comment]
> 看了一天，感觉完成度比较高，就是有几个问题， 1、缺失种子数据，自己做数据需要花费大量精力 2、前端跳转没太看明白，是通过反向代理请求后端吗，但是好像后端会把所有请求重定向掉，导致访问不到后端接口，前端是不是需要设置一些参数？

感谢关注，有时间了会继续更新。
1. 种子数据后续我会添加脚本文件
2. 这个问题应该是前端使用了 mock，可以在 [OpenAuthing-AdminUI](https://github.com/BeniceSoft/OpenAuthing-AdminUI) 项目中的 .umirc.ts 文件里把 `mock: false` 取消注释

**Comment by zengande** [comment]
已经修复了访问不到后端接口的问题，以及脚本在 scripts 目录下 @lostcc

**Comment by lostcc** [comment]
> 已经修复了访问不到后端接口的问题，以及脚本在 scripts 目录下 @lostcc

admin的密码是多少啊

**Comment by zengande** [comment]
> > 已经修复了访问不到后端接口的问题，以及脚本在 scripts 目录下 @zengande
> 
> admin的密码是多少啊

README 有写 用户名：admin 密码：123abc!
