### ISSUE TITLE
Migration 

### ISSUE THREAD

**Issue by eliasbui** [BeniceSoft/OpenAuthing#2]
how to using migraion generate tables in db mysql ?
![image](https://github.com/BeniceSoft/OpenAuthing/assets/88380128/767bafd0-dac3-492c-b11f-46870cb08508)

![image](https://github.com/BeniceSoft/OpenAuthing/assets/88380128/4dbb4bb8-fdfe-4ff2-8e9f-f8542fc7d873)

**Comment by zengande** [comment]
you can use this [script](https://github.com/BeniceSoft/OpenAuthing/blob/master/scripts/1%E5%88%9D%E5%A7%8B%E5%8C%96%E5%BB%BA%E8%A1%A8.sql) to migrate tables.
